/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a specialist a question; streams the answer as SSE */
        post: operations["post_chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Threads, or those matching a search */
        get: operations["list_threads_api_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One thread */
        get: operations["get_thread_api_threads__thread_id__get"];
        put?: never;
        post?: never;
        /** Delete a thread now */
        delete: operations["delete_thread_api_threads__thread_id__delete"];
        options?: never;
        head?: never;
        /** Pin or unpin a thread */
        patch: operations["change_thread_api_threads__thread_id__patch"];
        trace?: never;
    };
    "/api/imports/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exports in the data folder */
        get: operations["list_files_api_imports_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything imported, newest first */
        get: operations["list_imports_api_imports_get"];
        put?: never;
        /** Import one export from the data folder */
        post: operations["create_import_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Take an import back out, with its snapshots */
        delete: operations["delete_import_api_imports__batch_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts and recent entries */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        /** Create an account */
        post: operations["create_account_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a balance by hand */
        post: operations["record_balance_api_balances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/balances/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a balance entered by hand */
        delete: operations["delete_balance_api_balances__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training entered by hand */
        get: operations["list_training_api_training_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a workout by hand */
        post: operations["record_workout_api_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a workout entered by hand */
        delete: operations["delete_workout_api_workouts__workout_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/body-weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a body weight by hand */
        post: operations["record_body_weight_api_body_weights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/body-weights/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a body weight entered by hand */
        delete: operations["delete_body_weight_api_body_weights__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs, most recent first */
        get: operations["list_runs_api_model_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-log/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One run: every model call and tool run, verbatim */
        get: operations["read_run_api_model_log__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search-audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search egress audit */
        get: operations["list_entries_api_search_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preferences and the running configuration */
        get: operations["read_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/chat-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Choose the chat model; loaded now, in effect on the next question
         * @description Refused unless this card can run it; loaded at 8,192 tokens before the
         *     model it replaces is unloaded, so a refusal or a failed load changes
         *     nothing.
         */
        put: operations["choose_model_api_settings_chat_model_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change a preference; in effect on the next question */
        put: operations["write_preference_api_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Account */
        Account: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Currency */
            currency: string;
            /** Opened On */
            opened_on: string | null;
            /** Closed On */
            closed_on: string | null;
            /** Latest As Of */
            latest_as_of: string | null;
            /** Latest Balance */
            latest_balance: string | null;
        };
        /** AccountImported */
        AccountImported: {
            /** Label */
            label: string;
            /** Balance */
            balance: string;
            /** Holdings */
            holdings: number;
        };
        /** AccountListing */
        AccountListing: {
            /** Fixture Loaded */
            fixture_loaded: boolean;
            /** Kinds */
            kinds: string[];
            /** Accounts */
            accounts: components["schemas"]["Account"][];
            /** Recent */
            recent: components["schemas"]["Entry"][];
        };
        /**
         * Agent
         * @description A specialist named directly, bypassing the Steward.
         * @enum {string}
         */
        Agent: "tally" | "forge";
        /** Batch */
        Batch: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Source Label */
            source_label: string;
            /** Normalizer */
            normalizer: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Rows */
            rows: number;
            /** Status */
            status: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
        };
        /** BodyWeightOut */
        BodyWeightOut: {
            /** Id */
            id: number;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Weight */
            weight: string;
            /** Unit */
            unit: string;
        };
        /**
         * ChatRequest
         * @description Declared so the TypeScript client is generated rather than hand-written.
         */
        ChatRequest: {
            /** Message */
            message: string;
            agent?: components["schemas"]["Agent"] | null;
            /** Today */
            today?: string | null;
            /** Thread Id */
            thread_id?: string | null;
            /**
             * Detail
             * @default normal
             * @enum {string}
             */
            detail: "brief" | "normal" | "detailed";
            /** Rerun Of */
            rerun_of?: string | null;
        };
        /** ConfigItem */
        ConfigItem: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Locked */
            locked: boolean;
            /** Note */
            note?: string | null;
        };
        /** ConfigSection */
        ConfigSection: {
            /** Title */
            title: string;
            /** Items */
            items: components["schemas"]["ConfigItem"][];
        };
        /** Entry */
        Entry: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Balance */
            balance: string;
        };
        /** EntryOut */
        EntryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seq */
            seq: number;
            /** Kind */
            kind: string;
            /** Caller */
            caller: string;
            /** Model */
            model: string | null;
            /** Request */
            request: {
                [key: string]: unknown;
            };
            /** Response */
            response: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ExportFile */
        ExportFile: {
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Date In Name */
            date_in_name: string | null;
            /** Imported Batch */
            imported_batch: string | null;
            /** Imported As Of */
            imported_as_of: string | null;
        };
        /** ExportListing */
        ExportListing: {
            /** Data Dir */
            data_dir: string | null;
            /** Problem */
            problem: string | null;
            /** Fixture Loaded */
            fixture_loaded: boolean;
            /** Files */
            files: components["schemas"]["ExportFile"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Response models are declared because the TypeScript types are generated
         *     from this app's OpenAPI schema — an untyped response is an `any` in the UI.
         */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ImportOutcome */
        ImportOutcome: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Filename */
            filename: string;
            /** Source Label */
            source_label: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Rows */
            rows: number;
            /** Already Imported */
            already_imported: boolean;
            /** Accounts */
            accounts: components["schemas"]["AccountImported"][];
            /** Body Weights */
            body_weights: number;
        };
        /** ImportRequest */
        ImportRequest: {
            /** Filename */
            filename: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
        };
        /** ModelChoiceIn */
        ModelChoiceIn: {
            /** Model */
            model: string | null;
        };
        /** ModelOption */
        ModelOption: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Params */
            params: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Loaded Contexts */
            loaded_contexts: number[];
            /** Refused */
            refused: string | null;
            /** Measured */
            measured: boolean;
        };
        /** ModelsOut */
        ModelsOut: {
            /** Active */
            active: string;
            /** Default */
            default: string;
            /** Options */
            options: components["schemas"]["ModelOption"][];
            /** Unavailable */
            unavailable: string | null;
        };
        /** NewAccount */
        NewAccount: {
            /** Label */
            label: string;
            /** Kind */
            kind: string;
            /** Opened On */
            opened_on?: string | null;
        };
        /** NewBalance */
        NewBalance: {
            /** Account */
            account: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Balance */
            balance: string;
        };
        /** NewBodyWeight */
        NewBodyWeight: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Weight */
            weight: string;
        };
        /** NewSet */
        NewSet: {
            /** Exercise */
            exercise: string;
            /** Reps */
            reps: number;
            /** Weight */
            weight?: string | null;
        };
        /** NewWorkout */
        NewWorkout: {
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
            /**
             * Kind
             * @default strength
             */
            kind: string;
            /** Duration Minutes */
            duration_minutes?: number | string | null;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets?: components["schemas"]["NewSet"][];
        };
        /** PreferenceIn */
        PreferenceIn: {
            /** Value */
            value: number | string;
        };
        /** PreferenceOut */
        PreferenceOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Help */
            help: string;
            /** Value */
            value: number | string;
            /** Default */
            default: number | string;
            /** Allowed */
            allowed: (number | string)[];
        };
        /** Refusal */
        Refusal: {
            /** Kind */
            kind: string;
            /** Message */
            message: string;
        };
        /** RunDetailOut */
        RunDetailOut: {
            summary: components["schemas"]["RunSummaryOut"];
            /** Answer */
            answer: string | null;
            /** Answered By */
            answered_by: string | null;
            /** Entries */
            entries: components["schemas"]["EntryOut"][];
        };
        /** RunListing */
        RunListing: {
            /** Retention Days */
            retention_days: number;
            /** Runs */
            runs: components["schemas"]["RunSummaryOut"][];
        };
        /** RunSummaryOut */
        RunSummaryOut: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Thread Title */
            thread_title: string | null;
            /** Question */
            question: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Failed */
            failed: boolean;
            /** Chain */
            chain: components["schemas"]["StepOut"][];
        };
        /** SearchAuditEntryOut */
        SearchAuditEntryOut: {
            /** Id */
            id: number;
            /** Query */
            query: string;
            /** Allowed */
            allowed: boolean;
            /** Violation */
            violation: string | null;
            /** Result Count */
            result_count: number | null;
            /** Thread Id */
            thread_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchAuditListing */
        SearchAuditListing: {
            /** Entries */
            entries: components["schemas"]["SearchAuditEntryOut"][];
        };
        /** SettingsOut */
        SettingsOut: {
            models: components["schemas"]["ModelsOut"];
            /** Preferences */
            preferences: components["schemas"]["PreferenceOut"][];
            /** Configuration */
            configuration: components["schemas"]["ConfigSection"][];
        };
        /** SnippetPart */
        SnippetPart: {
            /** Text */
            text: string;
            /** Match */
            match: boolean;
        };
        /** StepOut */
        StepOut: {
            /** Kind */
            kind: string;
            /** Caller */
            caller: string;
            /** Tool */
            tool: string | null;
            /** Failed */
            failed: boolean;
        };
        /** StoredMessage */
        StoredMessage: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Agent */
            agent: string | null;
            /** Content */
            content: string;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCall"][] | null;
            /** Refused */
            refused: boolean;
            /** Confidence */
            confidence: string | null;
            /** Ungrounded */
            ungrounded: string[] | null;
            /** Detail */
            detail: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ThreadChange */
        ThreadChange: {
            /** Pinned */
            pinned: boolean;
        };
        /** ThreadDetail */
        ThreadDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Pinned */
            pinned: boolean;
            /** Messages */
            messages: components["schemas"]["StoredMessage"][];
        };
        /** ThreadListing */
        ThreadListing: {
            /** Retention Days */
            retention_days: number;
            /** Threads */
            threads: components["schemas"]["ThreadSummary"][];
        };
        /** ThreadSummary */
        ThreadSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Pinned */
            pinned: boolean;
            /** Snippet */
            snippet: components["schemas"]["SnippetPart"][] | null;
        };
        /** ToolCall */
        ToolCall: {
            /** Name */
            name: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Result */
            result?: string | null;
        };
        /** TrainingListing */
        TrainingListing: {
            /** Fixture Loaded */
            fixture_loaded: boolean;
            /** Unit */
            unit: string;
            /** Kinds */
            kinds: string[];
            /** Exercises */
            exercises: string[];
            /** Workouts */
            workouts: components["schemas"]["WorkoutOut"][];
            /** Body Weights */
            body_weights: components["schemas"]["BodyWeightOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkoutOut */
        WorkoutOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Performed On
             * Format: date
             */
            performed_on: string;
            /** Kind */
            kind: string;
            /** Duration Minutes */
            duration_minutes: string | null;
            /** Notes */
            notes: string | null;
            /** Sets */
            sets: components["schemas"]["WorkoutSetOut"][];
        };
        /** WorkoutSetOut */
        WorkoutSetOut: {
            /** Exercise */
            exercise: string;
            /** Set Number */
            set_number: number;
            /** Reps */
            reps: number;
            /** Weight */
            weight: string | null;
            /** Unit */
            unit: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    post_chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_threads_api_threads_get: {
        parameters: {
            query?: {
                /** @description Words to search for */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_api_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetail"];
                };
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    delete_thread_api_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    change_thread_api_threads__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    list_files_api_imports_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportListing"];
                };
            };
        };
    };
    list_imports_api_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"][];
                };
            };
        };
    };
    create_import_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOutcome"];
                };
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    delete_import_api_imports__batch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListing"];
                };
            };
        };
    };
    create_account_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAccount"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    record_balance_api_balances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewBalance"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    delete_balance_api_balances__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    list_training_api_training_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingListing"];
                };
            };
        };
    };
    record_workout_api_workouts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWorkout"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutOut"];
                };
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    delete_workout_api_workouts__workout_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    record_body_weight_api_body_weights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewBodyWeight"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyWeightOut"];
                };
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    delete_body_weight_api_body_weights__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: conflicts with what is recorded */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    list_runs_api_model_log_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Older than this start time */
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_api_model_log__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_search_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Older than this time */
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchAuditListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    choose_model_api_settings_chat_model_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelChoiceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    write_preference_api_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nothing by that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Refused: the input cannot be read as it stands */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
}
