"""measurement precision

Both of these columns are measurements, and both were declared nullable with a
bare Decimal annotation, which quietly inherited the money precision. The result
was body mass stored at three decimal places and a lifted weight at two -- the
same kind of value, recorded to different precision, for no reason anyone would
have chosen on purpose.

Harmless today because no real data exists yet. Much less harmless later.

Revision ID: d68e1bfcda46
Revises: fa7860f9535d
Create Date: 2026-09-18 20:19:55.329454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68e1bfcda46'
down_revision: Union[str, Sequence[str], None] = 'fa7860f9535d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'duration_minutes',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('workout_set', 'weight',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_set', 'weight',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('workout', 'duration_minutes',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
