"""initial schema

Revision ID: db1becaa84fe
Revises: 
Create Date: 2026-09-18 20:00:50.784120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db1becaa84fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('checking', 'savings', 'brokerage', 'retirement', 'credit', 'loan', 'cash', 'other')", name=op.f('ck_account_kind_known')),
    sa.CheckConstraint('closed_on is null or opened_on is null or closed_on >= opened_on', name=op.f('ck_account_closed_after_opened')),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_account_currency_is_iso_4217')),
    sa.CheckConstraint('length(label) > 0', name=op.f('ck_account_label_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account')),
    sa.UniqueConstraint('label', name=op.f('uq_account_label'))
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_sha256', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=False),
    sa.Column('normalizer', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'raw'"), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('raw', 'normalized', 'failed')", name=op.f('ck_import_batch_status_known')),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_import_batch_row_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch')),
    sa.UniqueConstraint('file_sha256', name=op.f('uq_import_batch_file_sha256'))
    )
    op.create_table('thread',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thread'))
    )
    op.create_table('balance_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_balance_snapshot_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_balance_snapshot_batch_id_import_batch'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_snapshot')),
    sa.UniqueConstraint('account_id', 'as_of', name=op.f('uq_balance_snapshot_account_id_as_of'))
    )
    op.create_index('ix_balance_snapshot_as_of', 'balance_snapshot', ['as_of'], unique=False)
    op.create_table('body_metric',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(metric) > 0', name=op.f('ck_body_metric_metric_not_empty')),
    sa.CheckConstraint('length(unit) > 0', name=op.f('ck_body_metric_unit_not_empty')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_body_metric_batch_id_import_batch'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_metric')),
    sa.UniqueConstraint('as_of', 'metric', name=op.f('uq_body_metric_as_of_metric'))
    )
    op.create_table('holding_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(symbol) > 0', name=op.f('ck_holding_snapshot_symbol_not_empty')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_holding_snapshot_account_id_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_holding_snapshot_batch_id_import_batch'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holding_snapshot')),
    sa.UniqueConstraint('account_id', 'as_of', 'symbol', name=op.f('uq_holding_snapshot_account_id_as_of_symbol'))
    )
    op.create_index('ix_holding_snapshot_as_of', 'holding_snapshot', ['as_of'], unique=False)
    op.create_table('import_row',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('row_number >= 1', name=op.f('ck_import_row_row_number_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_import_row_batch_id_import_batch'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row')),
    sa.UniqueConstraint('batch_id', 'row_number', name=op.f('uq_import_row_batch_id_row_number'))
    )
    op.create_table('message',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant', 'system', 'tool')", name=op.f('ck_message_role_known')),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_message_thread_id_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index('ix_message_content_fts', 'message', [sa.literal_column("to_tsvector('english', content)")], unique=False, postgresql_using='gin')
    op.create_index('ix_message_thread_id_created_at', 'message', ['thread_id', 'created_at'], unique=False)
    op.create_table('search_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('violation', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('allowed or result_count is null', name=op.f('ck_search_audit_refusal_has_no_results')),
    sa.CheckConstraint('allowed or violation is not null', name=op.f('ck_search_audit_refusal_has_reason')),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_search_audit_thread_id_thread'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_audit'))
    )
    op.create_index('ix_search_audit_created_at', 'search_audit', ['created_at'], unique=False)
    op.create_table('workout',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('strength', 'cardio', 'mobility', 'sport', 'other')", name=op.f('ck_workout_kind_known')),
    sa.CheckConstraint('duration_minutes is null or duration_minutes > 0', name=op.f('ck_workout_duration_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_workout_batch_id_import_batch'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout'))
    )
    op.create_index('ix_workout_performed_on', 'workout', ['performed_on'], unique=False)
    op.create_table('workout_set',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.Uuid(), nullable=False),
    sa.Column('exercise', sa.Text(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('weight_unit', sa.Text(), nullable=True),
    sa.CheckConstraint('(weight is null) = (weight_unit is null)', name=op.f('ck_workout_set_weight_has_unit')),
    sa.CheckConstraint('reps >= 0', name=op.f('ck_workout_set_reps_non_negative')),
    sa.CheckConstraint('set_number >= 1', name=op.f('ck_workout_set_set_number_positive')),
    sa.CheckConstraint('weight is null or weight >= 0', name=op.f('ck_workout_set_weight_non_negative')),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name=op.f('fk_workout_set_workout_id_workout'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_set')),
    sa.UniqueConstraint('workout_id', 'exercise', 'set_number', name=op.f('uq_workout_set_workout_id_exercise_set_number'))
    )
    op.create_index('ix_workout_set_exercise', 'workout_set', ['exercise'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_set_exercise', table_name='workout_set')
    op.drop_table('workout_set')
    op.drop_index('ix_workout_performed_on', table_name='workout')
    op.drop_table('workout')
    op.drop_index('ix_search_audit_created_at', table_name='search_audit')
    op.drop_table('search_audit')
    op.drop_index('ix_message_thread_id_created_at', table_name='message')
    op.drop_index('ix_message_content_fts', table_name='message', postgresql_using='gin')
    op.drop_table('message')
    op.drop_table('import_row')
    op.drop_index('ix_holding_snapshot_as_of', table_name='holding_snapshot')
    op.drop_table('holding_snapshot')
    op.drop_table('body_metric')
    op.drop_index('ix_balance_snapshot_as_of', table_name='balance_snapshot')
    op.drop_table('balance_snapshot')
    op.drop_table('thread')
    op.drop_table('import_batch')
    op.drop_table('account')
    # ### end Alembic commands ###
