"""Declarative base and the shared column types the conventions require.

The naming convention matters more than it looks: Alembic names constraints
after it, and unnamed constraints are the usual reason a downgrade cannot find
what it is meant to drop. Phase 1's exit criterion is that migrations go down
as cleanly as they go up.

Every money and measurement column below is NUMERIC. None is FLOAT, and none
ever should be — binary floating point cannot represent 0.10, and a net worth
assembled from rounding errors is worse than no net worth at all.
"""

import datetime as dt
import uuid
from decimal import Decimal
from typing import Annotated

from sqlalchemy import DateTime, MetaData, Numeric, Uuid, func, text
from sqlalchemy.orm import DeclarativeBase, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# --- shared column types ------------------------------------------------------

#: Primary key, generated by Postgres so a caller never has to invent one.
uuid_pk = Annotated[
    uuid.UUID,
    mapped_column(Uuid(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")),
]

#: Wall-clock time a row was written. Never confuse this with `as_of`, which is
#: the date a fact was true. The two diverge constantly with backfilled history,
#: and conflating them is how a trend silently misreports.
#:
#: Named `timestamp` rather than `created_at` because a column called
#: `created_at` shadows the alias inside a class body, and the next annotation
#: in that class then resolves to the column instead of the type.
timestamp = Annotated[
    dt.datetime,
    mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now()),
]

#: Currency amounts. Two decimal places, room for a balance no one here has.
money = Annotated[Decimal, mapped_column(Numeric(18, 2), nullable=False)]

#: Share counts and similar. Fractional shares go to eight places.
quantity = Annotated[Decimal, mapped_column(Numeric(24, 8), nullable=False)]

#: Unit prices, which carry more precision than the totals they produce.
price = Annotated[Decimal, mapped_column(Numeric(18, 6), nullable=True)]

#: Physical measurements: body mass, lifted load, distance.
measurement = Annotated[Decimal, mapped_column(Numeric(12, 3), nullable=False)]


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map = {
        uuid.UUID: Uuid(as_uuid=True),
        dt.datetime: DateTime(timezone=True),
        Decimal: Numeric(18, 2),
    }


#: A measurement that may be absent — a bodyweight set records no load. Spelled
#: out rather than left to the bare `Decimal` annotation, which falls back to
#: the money precision and would silently store a lift at two decimal places
#: while body mass kept three.
optional_measurement = Annotated[Decimal | None, mapped_column(Numeric(12, 3), nullable=True)]

#: Session length in minutes. Two places is ample; the point of naming it is
#: that the precision is chosen rather than inherited.
duration = Annotated[Decimal | None, mapped_column(Numeric(8, 2), nullable=True)]
